# Generated by Django 2.1 on 2018-08-23 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='deartment',
            new_name='department_id',
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
