# Generated by Django 2.1 on 2018-08-23 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_auto_20180823_0537'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='department_id',
            new_name='department',
        ),
    ]
